version: "3.6"

services:
  api:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/service-clashperk:latest
    container_name: api
    restart: always
    # build:
    #   context: .
    #   dockerfile: .docker/Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    hostname: api
    mem_limit: 1g

  api-02:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/service-clashperk:latest
    container_name: api-02
    restart: always
    # build:
    #   context: .
    #   dockerfile: .docker/Dockerfile
    env_file:
      - .env
    ports:
      - '8081:8080'
    hostname: api-02
    mem_limit: 1g

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   restart: always
  #   volumes:
  #     - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - .docker/certificate.pem:/etc/nginx/certificate.pem
  #     - .docker/certificate_key.pem:/etc/nginx/certificate_key.pem
  #   ports:
  #   - '443:443'
  #   depends_on:
  #   - api
    