version: "3.6"

services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: .docker/Dockerfile
    env_file:
      - .env
    hostname: api

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .docker/certificate.pem:/etc/nginx/certificate.pem
      - .docker/certificate_key.pem:/etc/nginx/certificate_key.pem
    ports:
    - '443:443'
    depends_on:
    - api
    